### ISSUE TITLE
Allow the use of emote icons as ring action icons

### ISSUE THREAD

**Issue by Trobador** [Tischel/TPie#11]
Hi, thank you for your work on TPie.

I was planning on using TPie for emotes. However, it seems that while you can use emotes through macros, you can't use their icon at the moment ; the icons for emotes do not appear in the icon selection GUI.

I'm certain many people would love to use TPie for easy access to emotes. Any way this could be added?

**Comment by Tischel** [comment]
You can use emote icons if you manually write down their icon IDs.
I'll add them to the icon browser though, since it seems like something people would look for.

**Comment by Tischel** [comment]
Added emote icons to the main browse tab in v0.3.0.0
