### ISSUE TITLE
Window border from Dalamud global theme shows on rings

### ISSUE THREAD

**Issue by Trobador** [Tischel/TPie#12]
Hi, thank you for your work on TPie.

![image](https://user-images.githubusercontent.com/35611827/146640146-b571d1a6-5b6f-421a-b5fc-8a117ca52817.png)

My Dalamud theme has a window border and it seems to show on rings. This is technically expected behaviour as rings are windows like any other, but it looks off, and I, as probably other users, would rather not have to change my global theme for a single plugin.

Would it be possible to add a setting to ignore window borders or styling altogether to prevent this ? I think it would be best to leave it on a toggle, as some might actually like being able to theme their rings.

**Comment by Tischel** [comment]
I'll fix it but I don't think there's a need for a toggle.
Highly doubt anyone would want to see that.

**Comment by Tischel** [comment]
Fixed in v0.3.0.0
