### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by Battler624** [Tischel/TPie#15]
I Posted this in the #plugin_suggestions on Goat server but i thought maybe this is a better place, so anyway thanks for the plugin its lovely but I still have a wishlist 
TPie Wishlist:
Rotation of the rings (Currently it starts from the right and clock wise, I prefer if it would start from the top and clock wise)
Options for Mounts and GeneralActions (Currently I use commands for them) /mount "Yol" & /ac "Sprint" <me>
Make the first item in the ring a quick action (so if I open the ring without moving the mouse, the first item in the ringwill be selected and used immediately) or add the option to choose one of the items as a quick action
Set global border thickness and radius

**Comment by Tischel** [comment]
Rotation setting and global border settings will be added in v1.0.0.0.

Regarding general actions / mounts the only reason why I haven't done it is because I need to figure out how to do it :P
Regarding the quick action, I don't think I want to add that. It'd bring some complications in the logic that I don't really want to deal with and I'm sure if I event want that functionality in general.

**Comment by Battler624** [comment]
Honestly the best feature is the quick action and it's the one I want the most and used the most in oPie. Idk if this is viable but maybe check if the user is holding the buttons within the first 100ms and if he is continue on with tPie and if not pass it to the game? (Thus the user simply puta whatever he wants on the game hotbar instead of creating quickaction specific logic if that is what's the issue)

**Comment by Tischel** [comment]
Passing the keybind to the game or not is not the issue (there's already a setting to handle this).
My concern is mostly with TPie's logic on the ring elements selection. I have a feeling this will cause a bunch of issues.

It's definitely doable, though.

**Comment by Battler624** [comment]
I know about the setting I meant it only passes the input if the user isn't actively holding the tPie buttons.

**Comment by Iaotle** [comment]
+1 on the quick action, that would be great

**Comment by tewan** [comment]
Came to see if quick action was something planned, definitely one of the features I'd like to see. 

Example usage scenario in my case would be having it bound to C for character screen, tapping it would open character screen or holding it would open different gear sets.

**Comment by Tischel** [comment]
Quick action added in v1.2.0.0
