### ISSUE TITLE
Allow side mouse button as keybind

### ISSUE THREAD

**Issue by nickieroonie** [Tischel/TPie#17]
Hello, seems like side mouse buttons do not work as keybinds - wondering if that would be possible to add this functionality? Thanks very much for creating the plugin! Have a good one

**Comment by starpotion** [comment]
Same here, would love to use my mouse buttons to activate my wheels as that's how I activate similar interfaces in other games.

**Comment by Tischel** [comment]
Added support for mouse buttons 3, 4 and 5 as possible keybinds in v1.2.0.0 (these usually are the 3 mouse wheel clicks, but depends on the hardware).

**Comment by nickieroonie** [comment]
Thanks so much!
