### ISSUE TITLE
Suggestion: add the ability to have multiple rings.

### ISSUE THREAD

**Issue by holodrum** [Tischel/TPie#2]
So that you have, for example, 3 rings, when using one shortcut, so that you have an inner ring, then an outer ring, and even further, one more outer ring! Like this -> ( ( ( ) ) )

I hope my beautiful demonstration/text example makes sense! :D

It would save space and at the same time give the user possibility to categorise their rings even further :)

**Comment by Tischel** [comment]
Definitely something I've thought of but its a pretty considerable effort to make it happen.
It might happen in the future, but no plans for this right now.

**Comment by holodrum** [comment]
Well, if it ends up being added, that would be absolutely amazing, but, even as it is now, the plugin is so damn good, it has made a lot of stuff way easier and is a huge improvement over "QoL Bar" and the way that I used that! :)

Anyway, since I already have you here, is there any way to do multi-lines in the macros, like what you can already do with the game built-in macros and in QoL Bar?

I want to create a macro that toggles multiple hotbars, but you can't do that on one line.

**Comment by Tischel** [comment]
Multilined macros will probably be supported in the future, but no ETA yet.

**Comment by cking** [comment]
> Definitely something I've thought of but its a pretty considerable effort to make it happen. It might happen in the future, but no plans for this right now.

i like how minemenu for minecraft (https://www.curseforge.com/minecraft/mc-mods/minemenu) does it

when you select an action, it opens a completly new ring, with the first action being "back" to return to previous ring.

if wanted, i could record a small animation.

**Comment by Tischel** [comment]
Nested rings added in v 1.1.0.0
