### ISSUE TITLE
Selecting Minion roulette icon crashes TPie

### ISSUE THREAD

**Issue by skullriot** [Tischel/TPie#26]
I created a ring with /mount "company chocobo", draught chocobo, sds fenrir, bomb palanquin, /ac "mount roulette" commands. 
I added a nested ring that I was going to put minions under. 
Selected add a nested ring, named the ring, and then went to the icon selector
upon selecting the minion roulette icon TPie crashes

other addons loaded are:
currency alert
delv ui
ez fauxhollows
ez mini cactpot
ez wondrous tails
fc name color
gatherbuddy
globetrotter
item search
nosoliciting
party list layout (testing)
qol bar
questaway
repairme
simpletweaks
soundsetter
tourist
triadbuddy
zodiacbuddy

**Comment by Tischel** [comment]
Please send me your log located in:

`%AppData%\Roaming\XIVLauncher\dalamud.log`
