### ISSUE TITLE
[BUG] Clicking Move Up/Down without an object crashes Tpie

### ISSUE THREAD

**Issue by Sythalin** [Tischel/TPie#27]
To Reproduce

1) create a ring
2) fill it with 2+ items
3) close Ring Settings window
4) reopen ring to edit
5) click on Move Up/Down arrow without selecting a menu item
6) all Tpie windows close, cannot be reopened
7) completely closing game and re-entering fixes

**Comment by Tischel** [comment]
Fixed in v1.3.1.0
