### ISSUE TITLE
"Quick Action" does not follow its target when list is reordered

### ISSUE THREAD

**Issue by Styggy** [Tischel/TPie#28]
Problem: When an icon list is reordered, the Quick Action check is treated as its own slot, rather than following the indicated icon.

Steps to Replicate: Check Quick action on a ring with multiple icons. Order the icon below your check to move up in priority, it will move into the Quick Action slot, rather than bypassing it.

Notes: This at first glance appears super useful given that you can't assign nested rings to the center, however the nested ring isn't accessible regardless. I wanted to put a "go back" button in the middle of the ring for nested rings, so potentially adding that would be good.

**Comment by Tischel** [comment]
Fixed in v1.3.1.0
