### ISSUE TITLE
Setting Gearsets by name revert back to gearset "1" when reloading or restarting.

### ISSUE THREAD

**Issue by SkylerMews** [Tischel/TPie#3]
When I set up a wheel for gearsets and find the gearsets via name, such as; "BRD", "WAR", "MCH", "BLM", they get reverted all to gearset "1" on reload/restart of plugin/game. I have to manually go back in within the settings for each gearset in the wheel and set them again. 

Version: 0.0.2.4

I love this mod so much, its extremely clean and smooth, I love everything about it, just only have this one issue with it, thank you for your hard work! 

Edit:

Here is my config for the wheel!
`|7JrdbtowFIDvJ/UdULTLLIKE0rI7QirIChFK6Fg37SIFd7UWkskJdGziyXaxR9orzPk/ZbHAV8ySuYF8/onj88mJw/nz6/fPi1etlvI62X1DytuWMp9hpE2jFQpizcXhF7WVEkXNajn+Oqv0LnqIC3SLdiYOV5RmHbG6KqrB3vLGtOJVuzweJiSg4NEPYlSyQZBQlJBNRbwn/JiU1VK2z4fi+iu8iWmBbrS1vE/FTtDawz9Q0/i8XUxLNWezRgQvY+09WiYR0dVWUTAjeOsnSBtGBE3wQzXqD7Rxr1ucgR7fF8dgKOlp05F8yqsUp2ZNzk2A1ihMYm2EfOKhpDh+OVm0cVFsW7SDTo3vYpQhOG117TJms4kFurKI/zxH36tprEtobPMT9GtmL6Mwgz39GnIzIitE6rk94RLTmcmbHV5eGv8oiA66Ox4w41jAim7SsJVeVPC+CX7MYc3yqBal8ye8/BqiOI0vbAj8K+E+/1E2/x80WAxcLg30TrMGkEsNhNPAcm+5NDD0Zg0glxqoomkwckw+Da4YGgAuNRBOg8V4yndT6DZrALnUQBVNA2845tPgmqEB4FID4TQYeHO+m4LRrAHkUgNVNA2mDt8jot5mrAaASw2E08ByR3waMHYKkEsNVNE0cGyH76bAWA0glxoIp4E34NspGIydAuRSA1U0DUyX72WyznhEhFxqIJwGU84No8F4mQy51EAVTQPLGfJpwHhvALnU4OwaXPJ6YE44XyNeMu4KgEsP1HN7wP2MOOXbKuiMPxUglxqcWwODVwPX4twqMFYDyKUGqmirgTm549Ogx9AAcKnBaRpc0K/PWdXD1JpjSTXdk7KgOjdv2mVYslSavtanH0rLpTvLpfmXLtLGLzKmZgRtMXqmGWe0qMr2Uux4sEzwNh1p7Ysy9mM73FJVI7IrU62KbLD9XwAAAP//AwA=`

**Comment by Tischel** [comment]
Fixed in v0.0.2.6
