### ISSUE TITLE
No Job icons on the Ring menu

### ISSUE THREAD

**Issue by AkiraVR** [Tischel/TPie#30]
Whenever i open the ring menu now the icons of the jobs set to the gearset do not show up its just empty
![image](https://user-images.githubusercontent.com/99085612/152647616-59319a2c-ae43-4d98-8a0a-68db41cc2f43.png)

tried removing the menu and re-adding but did not work, disabled and reinstalled the plugin as well but no fix so far.

**Comment by Tischel** [comment]
Your texture files likely got corrupted when you installed some mod.
Re-install the texture mods.
I'd recommend using Penumbra (3rd party plugin) rather than FFXIV TexTools to apply mods (Penumbra doesn't change the game files directly so there's no risk of corruption).

**Comment by AkiraVR** [comment]
I have already done this as well but it's all gone even after reinstalling MaterialUI :/
