### ISSUE TITLE
[BUG] Quick Action does not follow "Selection Background" setting

### ISSUE THREAD

**Issue by sasalx** [Tischel/TPie#32]
Hey. I noticed that when you create a ring with selection background off, it doesn't apply to action on "quick action". I also added two images to show what I am talking about. It's a minor bug but hopefully it can be fixed.
![ss1](https://user-images.githubusercontent.com/13791917/158493401-4e79e286-b333-4c19-a937-633056e371d2.PNG)
![ss2](https://user-images.githubusercontent.com/13791917/158493403-17253b92-eb92-41f1-8962-a38719871322.PNG)

**Comment by Tischel** [comment]
Fixed in v1.3.1.0
