### ISSUE TITLE
Bug / Suggestion : Material UI not showing Job Icons

### ISSUE THREAD

**Issue by RyudoGaming** [Tischel/TPie#37]
So I am using Material UI, which replaces the 4k UI with a custom one, problem is when trying to use TPie it doesn't show any Icons,

I have found a way around it by making a bunch of commands and finding Icons similar but they're not the same ones :(

![image](https://user-images.githubusercontent.com/39316798/166828285-6255a960-f09b-46cc-8436-cf2d3c6abaa4.png)

I don't know if its something to do with the modded UI or the fact I am using the HD UI in general but would be cool to have it working with it ^^. 

EDIT

as you can see none of the gear sets have icons with them. 

![image](https://user-images.githubusercontent.com/39316798/166828618-83364ba2-008d-4e26-a363-fdf7f60bf813.png)

**Comment by Tischel** [comment]
Your texture mods corrupted your game files.
Remove them / re-install them.

**Comment by RyudoGaming** [comment]
Thanks, whilst a reinstallation didn't work I updated it to the newest one and it's all working now! 

Thanks again for the awesome mod! 
![image](https://user-images.githubusercontent.com/39316798/166884381-4de41aca-4f9e-4684-b10c-4279957eab04.png)
