### ISSUE TITLE
Suggestion: Multiple keybinds for single ring

### ISSUE THREAD

**Issue by lorecast162** [Tischel/TPie#39]
One example I have is my job select ring.
At home I have my gaming pc which has a mouse with sidebuttons, which makes the most sense to use for me, but when I'm out (i.e. during a break) I have my laptop with me with a smaller mouse which doesnt have those sidebuttons, so binding it to a keyboard key (I have it currently mapped to Z) would solve the lack of extra mouse buttons.

**Comment by Tischel** [comment]
Unlikely I implement this.
I'd suggest just duplicating the ring and assigning another key to the duplicate.
