### ISSUE TITLE
Allow mouse buttons 3/4/5 as keybinds

### ISSUE THREAD

**Issue by NyoroRhaeven** [Tischel/TPie#4]
Love this mod but would be amazingly more useful if we could bind wheels to mouse!

**Comment by SkylerMews** [comment]
Oooh! I didn't even think of this! Clever!

**Comment by Valnoressa** [comment]
Would love this too! Especially letting us bind it to the middle mouse button.

**Comment by Tischel** [comment]
Added in v1.2.0.0
