### ISSUE TITLE
Rings are no longer displayed

### ISSUE THREAD

**Issue by Flavescent** [Tischel/TPie#45]
For a few days now, the ring menus generated by TPie are no longer being displayed for me. They are still generated - and can be navigated and used - but are invisible. How can I help debug this?

**Comment by jackolas-lock** [comment]
I know this is old, but for anyone else experiencing this, having the "Enable multi-monitor windows" setting turned on (/xlsettings > Look & Feel) seems to be causing this problem. Which is a huge bummer, because I really like having that setting.
