### ISSUE TITLE
TPie kinks related to set names?

### ISSUE THREAD

**Issue by FeaEaXIV** [Tischel/TPie#48]
Hi all,
I've been running into a bunch of issues trying to assign gear sets onto TPie.

1. I cannot name a gearset a number like 840. When I add the gearset to a ring and try to access it, I get the error
`"840" is not a valid gear set number`. It seems like the game is forcing the name to be parsed as a set number?

2. I have issues having gear set names that incorporate numbers. Given four sets `BLM`, `BLM 884`, `BLM 2171`, and `BLM EUREKA`, I can only succesfully switch to the ones without numbers. Attempting to access the others gives me a random Sage set (my third gearset, if that's at all useful information), along with the error `Incorrect glamour plate number`.

3. Given two sets of similar naming e.g.  `UCOB SPS` and `UCOB CRIT`, adding both to a ring ends up pointing both TPie buttons at whichever one comes first in the FFXIV gear set list. Reversing their order in the gear set list switches the pointer. The order in the TPie ring does not appear to matter. I'm imagining this is due to some sort of naming disambiguation, since the game does not prohibit the creation of multiple gear sets with the same name?

I'd like to be able to consistently assign gear sets across multiple characters (since TPie does not have character-based profiles and is account-wide), and denote things like spellspeed/skillspeed or gcd tier where relevant, but I've had this hurdle for a while now.

Thanks for your work on this plugin (and your other work)! If you need more information I'll be happy to provide.

EDIT:
Everything behaves well if I remove whitespace. I realized that `DSR 884` was switching to the SGE set named `DSR`.

**Comment by Tischel** [comment]
Fixed in v1.8.0.1
