### ISSUE TITLE
Don't use Hotbar Keybinds

### ISSUE THREAD

**Issue by Megasder** [Tischel/TPie#5]
I was using QOLbars until I discovered TPie, however TPie has a problem that QOLbars doesn't have.

When you use a keybind that is already used in a hotbar you use that hotbar keybind first (for example, I put my TPie hotbar into Ctrl + Alt + 3 and I have a hotbar with Alt + 3 and Ctrl + 3, with QOLbars if I press Ctrl + Alt  + 3 only the QOLbar appears, my hotbar skill is not used, however in TPie if I press Ctrl + Alt + 3 it will do the Alt + 3 Skill and then the circle appear

![1](https://user-images.githubusercontent.com/92712466/145441313-be5ba735-60f1-426d-a614-9aa5323055e6.JPG)
The image is not really clear sorry... but I think you can see that my Alt + 3 is glowing because is like im pressing it and my PTie circle is also there.

![2](https://user-images.githubusercontent.com/92712466/145441762-69a30695-fb95-4880-8aea-328937da00b8.JPG)
And now the same keybind with the QOLbar and you can see that the Alt + 3 is not glowing, that is what I want.

Thank you for this amazing plugin :)

**Comment by Tischel** [comment]
Version 0.1.1.0 introduces a keybind passthrough setting to solve this issue.

**Comment by Megasder** [comment]
I already posted this on the discord but just in case.

I Tried it but it seems it does the same as before.
![unknown](https://user-images.githubusercontent.com/92712466/145694592-affe6088-ae52-4f2b-8311-a2847b7b9a2b.png)

**Comment by Tischel** [comment]
you want it disabled
