### ISSUE TITLE
TPie fails to install

### ISSUE THREAD

**Issue by Kynet1c** [Tischel/TPie#50]
Hi, i tried to install TPie, but keep getting and installation error. Restarting does not help.

[dalamud_tpie.log](https://github.com/Tischel/TPie/files/12388635/dalamud_tpie.log)

**Comment by Tischel** [comment]
Known issue, it has been fixed in v1.7.1.1 but that version hasn't been merged into Dalamud yet.

In the meantime you can install the Wotsit plugin to prevent this issue from happening.
