### ISSUE TITLE
Custom Icons or Penumbra Interface Collection Icon Override

### ISSUE THREAD

**Issue by Slip-Up** [Tischel/TPie#56]
Would it be possible to allow the use of custom icon files?  I'd like to use modified job icons with TPie, but i'm only seeing the vanilla icons in the icon browser.  If penumbra integration is supported, it's not working for me with TPie, but does work with QOLbar.

**Comment by Triksterism** [comment]
I've been curious about this myself. Maybe there's a way by using the correct icon ID but I haven't found a list yet.

**Comment by Tischel** [comment]
Implemented in v1.10.0.1
