### ISSUE TITLE
Suggestion: Hitbox around each item in a ring

### ISSUE THREAD

**Issue by ExtraThicc1993** [Tischel/TPie#6]
First of all: loving the plugin, feels almost identical to Opie from WoW. What would make using it quite a lot more convenient would be if there was some kind of invisible hitbox around the items in each ring. I often catch myself not "aiming" the cursor properly and landing in between items, which makes me not choose one at all. Thats a thing I always liked about Opie back in the day, you would basically always choose an item when you press your keybind and drag your cursor into any direction.

If there was any way you could make this happen without an enormous effort on your end that would be amazing!

**Comment by Tischel** [comment]
I thought it was already pretty lenient.
Can you share a ring where this happens to you?

TPie doesn't guarantee that there's always one option selected and I'm not sure I want that, but I could make it more lenient if needed.

**Comment by ExtraThicc1993** [comment]
|7JfdbtMwFMfvkfYOVsRlCU3aTYO7fiAIW6eq3fgcF15yulp1YmQ7nTLUJ+OCR+IVZsdOkwamQi4QlXLVnr+Pj4/9i9P+f37/8e3oCULOU5l9Beclci6nBNwJi4AKd0aS2w7SitPJsy5wnCdNWJpIYcUzyIYkiZSel3qsmE2r1jOTVeKpV8QjyakSFpgKKLQBlXVpviSLrai1jellhiOSCjXgHXfdrtECCfGc3MPvGpxnQo26F2kMnITCfQehZNzvIDsw5WSNJbgjxuGc3Gzb/qAm94sVVPzRxpVWxhzfnZNELyN5CqU4B6pWISwZ4nB1y9VRRjs5ul+9hc+mtu35sWN9RSEGBcOd4JAzG+0ecgVcRRqxOMb50s7zWPNE184ZjtMMsQWSS0CJah5JTKi4dlBlot7DkPEIeI2K7j1kSTDWh+H1vVLepm83s3c7+hTMtPpm8t4pq5XbT7W3j6oto9mWaK2oAf8ifjJiqRn0dvRyScJVAkKz7FUHtg+pX4gb86WY/i+Rv8Y3nABFE8xXKAiCRqxfHLesD4D1gD4jK0poE8Z+t3z42/vc+28ZXy2IJI0u8clpC/gALvGYRawRX99v+R4A3xmWS0xZsz9dfvtDfAiM36YQNXtJ+yftJf5bwEfq44vxVjXjsM8y9P/ICHq7PrASaoNQCd+bUEfWJE45rAncKZ+9Q90JxEBZxLVuraK+wSJI1uq5YzwrXKJ1wJsHAAAA//8DAA==

That would be the ring in question (although I  am having this issue with all of my rings). There is quite a big "gap" between the objects where they kind of "light up" but aren't yet selected.

**Comment by Tischel** [comment]
Should be easier to select things in v0.3.0.0 (no setting though)
