### ISSUE TITLE
Allow for tooltip label when hovering over ring icons.

### ISSUE THREAD

**Issue by ryankhart** [Tischel/TPie#8]
I plan on using this plugin for seldom-used options, so I might not always remember an action or item by its icon, so it would be nice to show some hint text as a tool tip when hovering over the icons.

**Comment by Tischel** [comment]
Are you talking about macros? Would you like to see the actual macro in a tooltip?
I like the idea but I'm not sure what I'd show in the tooltip.

**Comment by Trobador** [comment]
I personally would prefer to see the action name in a tooltip rather than on the icon itself, so that could be an use for it.

**Comment by Tischel** [comment]
Added a ring setting to enable tooltips.
When hovering on an item the tooltip will show a short description (same stuff you see on the elements table in the rings setting).

Example:
![image](https://user-images.githubusercontent.com/6404136/146992416-c05d9dfe-7a36-45fd-b55e-fa5090d64b7b.png)


Added in v1.0.0.0
